_wandb:
    value:
        cli_version: 0.23.0
        e:
            qo96usfm8xxsbrgj8c9a2b7n2pl9fj1d:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                codePath: /Users/MicheleMarschner/Documents/Uni/WiSe_2025_26/Applied CV/Applied-Computer-Vision-Projects/Multimodal_Learning_02/notebooks/01_dataset_exploration.ipynb
                codePathLocal: 01_dataset_exploration.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "110333239296"
                email: michele.marschner@gmail.com
                executable: /opt/anaconda3/envs/aCV/bin/python
                git:
                    commit: d3ab73b1424ad14fe026fa60bd3d61daf6b25d18
                    remote: https://github.com/MicheleMarschner/Applied-Computer-Vision-Projects.git
                host: MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.4-arm64-arm-64bit-Mach-O
                program: /Users/MicheleMarschner/Documents/Uni/WiSe_2025_26/Applied CV/Applied-Computer-Vision-Projects/Multimodal_Learning_02/notebooks/01_dataset_exploration.ipynb
                python: CPython 3.14.0
                root: /Users/MicheleMarschner/Documents/Uni/WiSe_2025_26/Applied CV/Applied-Computer-Vision-Projects/Multimodal_Learning_02/notebooks
                startedAt: "2025-11-23T12:33:31.457353Z"
                writerId: qo96usfm8xxsbrgj8c9a2b7n2pl9fj1d
        m: []
        python_version: 3.14.0
        t:
            "3":
                - 2
                - 16
            "4": 3.14.0
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 10
learning_rate:
    value: 0.01
